stages:
  - build
  - test

job_build:
  stage: build
  script:
  - meteor npm install
  only:
  - master
  tags:
  - master

job_test:
  stage: test
  script:
  - echo "testing ----"
  - meteor npm test
  only:
  - master
  tags:
  - master
