before_script:
  - echo "======================================"
  - echo "==== START auto full script v0.1 ====="
  - echo "======================================"

stages:
  - build
  - test

job_build:
  stage: build
  script:
  - cd
  - call meteor npm install
  only:
  - master
  tags:
  - master

job_test:
  stage: test
  script:
  - echo "testing ----"
  - call meteor npm test
  only:
  - master
  tags:
  - master
